# ACI playbook - L2-BD and EPG Creating and binding.
# Here we expecting Tenant, VRF, PhyDOM and names are pre-configured
---
- name: L2-BD and EPG Creating and binding
  hosts: apic
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: "{{ aci_validate_certs }}"

  vars_files:
    - variables.yaml

  tasks:
    - name: Add Bridge Domain
      cisco.aci.aci_bd:
        <<: *aci_login
        tenant: "{{ tenant }}"
        bd: "{{ bd }}"
        vrf: "{{ vrf }}"
        name_alias: "{{ alias_bd }}"
        description: "{{ description_bd }}"
        enable_routing: false        
        state: present
      delegate_to: localhost


    - name: Add a new AP
      cisco.aci.aci_ap:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ AppProfile }}"
        state: present
      delegate_to: localhost

    - name: Add a new EPG
      cisco.aci.aci_epg:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ AppProfile }}"
        epg: "{{ epg_name }}"
        name_alias: "{{ alias_epg }}"
        description: "{{ description_epg }}"
        bd: "{{ bd }}"
        state: present
      delegate_to: localhost

    - name: Add a new physical domain to EPG binding
      cisco.aci.aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant }}"
        ap: "{{ AppProfile }}"
        epg: "{{ epg_name }}"
        domain: "{{ phy_domain }}"
        domain_type: "{{ domain_ty }}"
        state: present
      delegate_to: localhost
